#TX5_DIR = "C:/cygwin64/home/Edward_Wu/SourceCodes/Future/tx1_data"
TX1_DIR = "/Users/edward_cc_wu/SourceCode/Future/tx1_data"
#TX5_DIR = "C:/cygwin64/home/Edward_Wu/SourceCodes/Future/tx5_test"
TX5_DIR = "/Users/edward_cc_wu/SourceCode/Future/tx5_test"
#TX_DAILY_DIR = "C:/cygwin64/home/Edward_Wu/SourceCodes/Future/out/daily.txt"
TX_DAILY_DIR = "/Users/edward_cc_wu/SourceCode/Future/out/daily.txt"